version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - workshop:/var/lib/mysql
    env_file:
      - ./.env
    ports:
      - 3307:3306
  app: 
    depends_on:
      - db
    image: pc-workshop
    ports:
      - 5000:5000
    restart: always
    env_file:
      - ./.env

volumes:
  workshop: {}